#ifndef PEAKSCHOOSER_GLOBAL_H
#define PEAKSCHOOSER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PEAKSCHOOSER_LIBRARY)
#  define PEAKSCHOOSERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PEAKSCHOOSERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PEAKSCHOOSER_GLOBAL_H
